application: sdatcrm
version: live
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  expiration: "10d"

- url: /static
  static_dir: static
  expiration: "1s"

- url: /.*
  script: _go_app
  login: admin
